name: Tag

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Github Tag
      uses: mathieudutour/github-tag-action@v2
      with:
        # Required for permission to tag the repo.
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        default_bump: minor
        tag_prefix: v
        release_branches: master
